version: '3'
services:

  kibana:
      image: docker.elastic.co/kibana/kibana:8.8.0
      container_name: kibana
      restart: unless-stopped
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        # - elasticsearch.ssl.verificationMode=*none*
        # - I18N_LOCALE=zh-CN
      ports:
        - 5601:5601
      networks:
        - efk_service

networks:
  efk_service:
    external: true