version: "3"
services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    restart: unless-stopped
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # 不信任的ssl憑證
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - efk_service

networks:
  efk_service:
    external: true
