version: "3"
services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    restart: unless-stopped
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      # 首次啟動時 會自動選出一個適合當master的節點,因此須設定適合當master的節點
      - cluster.initial_master_nodes=es01
      # 集群中的节点可以彼此发现并选举一个主节点,因此不能寫自己
      - discovery.seed_hosts=es02,es03
      # 不信任的ssl憑證
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    # volumes:
      # - data01:/usr/share/elasticsearch/data
    # 一定要加 不然進程數過大 會導致node拉不起來
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - efk_service

  es02:
    # es01須先拉起來 才拉es02
    depends_on:
      - es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    restart: unless-stopped
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      # - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      # 不信任的ssl憑證
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    # volumes:
      # - data02:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - efk_service

  es03:
    depends_on:
      - es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    restart: unless-stopped
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      # - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      # 不信任的ssl憑證
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    # volumes:
      # - data03:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - efk_service

# volumes:
#   data01:
#     driver: local
#   data02:
#     driver: local
#   data03:
#     driver: local

networks:
  efk_service:
    external: true